name: Embedded C Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get install -y gcc

      - name: Build and run all tests
        run: |
          gcc motor.c speed.c fuel.c dtc.c can.c test.c -o test_runner
          ./test_runner

      - name: Build and run CAN tests
        run: |
          gcc can.c test_can.c -o test_can
          ./test_can

      - name: Build and run DTC tests
        run: |
          gcc dtc.c test_dtc.c -o test_dtc
          ./test_dtc